# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="random"
#ZSH_THEME="jonathan"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

#export GOPATH=$HOME/GITHUB/golib:/Users/Ray/Workspace/sandbox/go:$HOME/GITHUB/learning_golang
export GOPATH=$HOME/GITHUB/golib
#export GOROOT=/usr/local/go
#export GOBIN=$GOROOT/bin

PATH=$PATH:$HOME/.rvm/bin:$GOPATH/bin # Add RVM to PATH for scripting
export PATH=/opt/local/bin:$PATH
export PATH=/opt/local/sbin:$PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session. ]]

export LANG=zh_CN.UTF-8

#alias ios_ie_root='cd /Users/Ray/WorkSpace/IE/'
alias ios-ge-v1-root='cd /Users/Ray/WorkSpace/GE/Generation_1/ios'
alias ios-ge-v2-root='cd /Users/Ray/WorkSpace/GE/Generation_2/ios'
alias android-ge-v1-root='cd /Users/Ray/WorkSpace/GE/Generation_1/android'
alias android-ke-v1-root='cd /Users/Ray/WorkSpace/KE/Generation_1/android'
alias tap4fun-server='cd ~/WorkSpace/Server'

#local
alias r187='rvm use ruby-1.8.7@rails-3.0.5'
alias r193='rvm use ruby-1.9.3@rails-3.2.8'
alias r193_1='rvm use ruby-1.9.3@rails-3.2.6'
alias rvm_github='rvm use ruby-1.9.3@rails-github'

#redis-server /usr/local/etc/redis.conf
alias start-rails-servic='sudo /Library/StartupItems/MySQLCOM/MySQLCOM restart && redis-server  /usr/local/etc/redis.conf && redis-server /usr/local/etc/redis_6380.conf'
alias start-mysql-client='/usr/local/mysql/bin/mysql -uroot'

#alias ctags='/usr/local/bin/ctags'
export SVN_EDITOR=vim
alias stagin_an_ke_deploy='cap deploy an_staging'
#取消zsh的自动修正
setopt CORRECT

alias alias_update='~/WorkSpace/Server/server-alias/ && git pull'
#source ~/WorkSpace/Server/server-alias/ie.server
source ~/WorkSpace/Server/server-alias/ge.server
source ~/WorkSpace/Server/server-alias/android-ge.server
source ~/WorkSpace/Server/server-alias/android-ke.server
man() {
  env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}
